name: Pull submodules

on:
  schedule:
    - cron: '11 22 * * *'

jobs:
  commit:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Pull
        run: git pull --recurse-submodules
      - name: Diff
        id: diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m 'git pull --recurse-submodules'
          git push
        if: steps.diff.outcome == 'failure'
